- name: iterm folder
  file:
    path: "~/.iterm"
    state: directory
    mode: 0755

- name: Copy iterm settings
  file:
    src: "{{ item }}"
    dest: "~/.iterm/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./com.googlecode.iterm2.plist

- name: Set Defaults
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "~/.iterm"
    state: present

- name: Set Defaults 2
  osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present
