repos:
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v3.4.15
    hooks:
    -   id: ansible-lint
        files: ansible/\.(yaml|yml)$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
