# Creates the folders, and symlinks the needed files.

# There doesn't apparently appear to be a good way to recursively fetch a list of folders
# in ansible, so do a workaround to fetch the folders we will create.
- name: Fetch dotfiles folders
  command: "find . ! -path . -type d"
  args:
    chdir: "{{ role_path }}/files"
  register: folders
  changed_when: False

- name: Ensure dotfile folders exist
  file:
    path: "{{ home }}/{{ item }}"
    state: directory
    mode: 0755
  # TODO: Refactor default http://stackoverflow.com/a/41683255/4396258
  # http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals
  with_items: "{{ folders.stdout_lines | default([]) }}"

- name: Fetch dotfiles files
  command: "find . ! -path . -type f"
  args:
    chdir: "{{ role_path }}/files"
  register: files
  changed_when: False

- name: Symlink dotfiles
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  with_items: "{{ files.stdout_lines | default([]) }}"
