#!/bin/bash
vol=$(
    pactl list sinks | \
    grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | \
    tail -n 1 | \
    sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
)

echo "$vol%"

if [[ ! -z "$BLOCK_BUTTON" ]]; then
    i3-msg exec --no-startup-id pavucontrol
fi
