- name: dotfiles
  block:
    - name: facts
      set_fact:
        dotfiles: "{{ playbook_dir }}/roles/common/dotfiles/files"

    - name: Copy dotfiles
      copy:
        src: "{{ dotfiles }}/"
        dest: "~"
        mode: 0664

    - name: Set .gitconfig
      template:
        src: "{{ dotfiles }}/../templates/.gitconfig.j2"
        dest: "~/.gitconfig"
        mode: 0664

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3

    - name: Dotfiles venv
      pip:
        virtualenv: "~/.config/dotfiles/venv"
        virtualenv_python: python3
        requirements: "~/.config/dotfiles/requirements.txt"
        state: latest
