- name: GitApps folder
  file:
    path: "~/GitApps"
    state: directory
    mode: 0755

- name: Install Common GitApps
  git:
    repo: "{{ git_app.url }}"
    dest: "{{ git_app.dest }}"
    clone: yes
    update: yes
    depth: 1
  with_items:
    - {
        url: "https://github.com/robbyrussell/oh-my-zsh.git",
        dest: "~/GitApps/oh-my-zsh",
      }
    - {
        url: "https://github.com/Yelp/aactivator.git",
        dest: "~/GitApps/aactivator",
      }
    - {
        url: "https://github.com/junegunn/fzf.git",
        dest: "~/GitApps/fzf",
      }
  loop_control:
    loop_var: git_app

- name: Post Install Tasks
  command: ./install --no-update-rc --completion --key-bindings
  args:
    chdir: "~/GitApps/fzf"
  changed_when: False
