- name: facts
  set_fact:
    files: "{{ playbook_dir }}/ansible/roles/common/neovim/files"

- name: Set nvim config dir
  file:
    path: "~/.config/nvim"
    state: directory
    mode: 0755

- name: Set nvim config
  copy:
    # For some reason, this doesn't work with a relative path (?)
    src: "{{ files }}/init.vim"
    dest: "~/.config/nvim/init.vim"
    mode: 0664

- name: Set vim config
  copy:
    # For some reason, this doesn't work with a relative path (?)
    src: "{{ files }}/init.vim"
    dest: "~/.vimrc"
    mode: 0664

- name: nvim folders
  file:
    path: "~/.local/share/nvim/site/autoload"
    state: directory
    mode: 0755

- name: install plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: nvim venv
  pip:
    virtualenv: "~/.config/nvim/venv"
    virtualenv_python: python3
    name:
        - jedi
        - neovim
    state: latest

- name: vim folders
  file:
    path: "~/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - backup_files
    - swap_files
    - undo_files

- name: install plugins
  command: nvim +PlugInstall +qall --headless
  changed_when: False
