- name: Run roles
  include_role:
    name: '{{ item }}'
  loop:
    - 'homebrew'
    - 'common/dotfiles'
    - 'common/neovim'
    - 'common/apps'
    - 'macos/yabai'
    - 'macos/vscode'
    - 'macos/iterm2'