- name: Update Homebrew
  homebrew: 
    update_homebrew: yes

- name: Homebrew Install Packages
  homebrew: name={{ item }} state=latest
  with_items:
    - ffmpeg
    - iperf
    - neovim/neovim/neovim
    - ssh-copy-id
    - tmux
    - wget
