- name: Copy settings
  file:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./.skhdrc
    - ./.yabairc

- block:
  - name: Run role
    include_role:
      name: geerlingguy.homebrew
    vars:
      homebrew_installed_packages:
        - koekeishiya/formulae/skhd
        - koekeishiya/formulae/yabai

- name: Start brew services
  command: "/usr/local/bin/brew services start {{ item }}"
  with_items:
    - skhd
    - yabai
  changed_when: False
