- name: Copy settings
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./.skhdrc
    - ./.yabairc

- name: Install brew packages
  homebrew: name={{ item }} state=latest
  with_items:
    - koekeishiya/formulae/skhd
    - koekeishiya/formulae/yabai

- name: Start brew services
  command: "/usr/local/bin/brew services start {{ item }}"
  with_items:
    - skhd
    - yabai
  changed_when: False
