---
- name: cistern
  hosts: all
  roles:
    - bootstrap
    - { role: personal_server, when: "'ubuntu_personal_server' in group_names" }
    - { role: macos, when: "ansible_os_family == 'Darwin'" }
