- hosts: localhost
  vars:
    - user: "{{ lookup('env','USER') }}"
    - home: "{{ lookup('env','HOME') }}"

  roles:
    # Run 'bootstrap' first to get env info
    # TODO: better way of doing this?
    - bootstrap

    # Run common stuff
    - common/dotfiles
    - common/neovim
    - common/scripts
    - common/apps
    - common/crontab
    - common/virtualenv

    # Arch Stuff
    - { role: arch/dotfiles, when: is_arch }
    - { role: arch/system-files, when: is_arch }
    - { role: arch/systemd, when: is_arch }
    - { role: arch/pacman, when: is_arch }

    # OS X Stuff
    - { role: macos/chunkwm, when: is_mac }
    - { role: macos/homebrew, when: is_mac }
    - { role: macos/vscode, when: is_mac }
    - { role: macos/hyper, when: is_mac }
    - { role: macos/iterm2, when: is_mac }
