- name: Copy vscode settings
  file:
    src: "{{ item }}"
    dest: "~/Library/Application Support/Code/User/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./settings.json

- name: VSCode Extensions
  command: "/usr/local/bin/code --install-extension {{ item }}"
  with_items:
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - flowtype.flow-for-vscode
    - formulahendry.code-runner
    - joebateson.yelpcheetah
    - MarkLarah.pre-commit-vscode
    - vscodevim.vim
    - trinm1709.dracula-theme-from-intellij
    - ms-vscode-remote.remote-ssh
  changed_when: False
