#!/bin/bash
status=$(/usr/bin/acpi -b)
percent="$(echo $status | grep -o '[0-9]\{1,3\}%' | tr -d '%')"

if [[ $status == *'Discharging'* ]]; then
	echo "⚡ $percent%";
elif [[ $status == *'Charging'* ]]; then
	echo "  $percent%";
elif [[ $status == *'Full'* ]]; then
    echo "✔️  100%";
else
	echo "?  $percent%";
fi
